### ISSUE TITLE
Use xeniteu/postgres docker images

### ISSUE THREAD

**Issue by thijslemmens** [xenit-eu/start.xenit.eu#1]
Currently we still point to our hub.xenit.eu images, which are not public or up to date.
We should update to xeniteu/postgres:latest

**Comment by tgeens** [comment]
@thijslemmens Your PR #2 mentions this issue, but does not resolve this issue ? I don't know that was intentional :-)

**Comment by thijslemmens** [comment]
@tgeens not intentional

**Comment by tgeens** [comment]
Resolved by PR #4
